export const FETCH_COMICS_START = 'FETCH_COMICS_START';
export const FETCH_COMICS_SUCCESS = 'FETCH_COMICS_SUCCESS';
export const FETCH_COMICS_FAIL = 'FETCH_COMICS_FAIL';
export const SELECTED_CHARACTER = 'SELECTED_CHARACTER';